name: Hello Local

on:
  workflow_dispatch:
  push:

jobs:
  teste-basico:
    runs-on: ubuntu-latest
    steps:
      - name: Mensagem inicial
        run: echo "Iniciando testes locais"

      - name: Versao Node
        run: node -v

      - name: Final
        run: echo "Finalizado com sucesso!"
